### PR TITLE
Better support for nested elements and custom element handler

### PR DESCRIPTION
**Pull request by kmaschke85**
Hi,
thanks for your awesome BB code implementations. To be able to handle particular cases with BB code, I needed to add some stuff to your project. One case was an unexpected handling of nested elements like [ul][li]. The other case is that I needed to handle [img] tags. For that I had to create the NSAttributedString in a different way.
Would be nice if you would add my changes, so that I can add it to my project via cocoapods again.

### CODE REVIEW

**Comment by mrataj** [comment]
Thanks for your contribution! I have one question before merging this pull request. Can you show me example implementation of getCustomDefinedAttributedString? I want to know why getAttributesForElement didn't satisfy your requirements.

**Comment by kmaschke85** [comment]
Sure! I needed to initialize an NSAttributedString with an attachment like here:

``` objectivec
- (NSMutableAttributedString *)getCustomDefinedAttributedString:(BBElement *)element {
    if ([element.tag hasPrefix:@"img"]) {
        NSTextAttachment * attachment = [[NSTextAttachment alloc] init];
        attachment.image = [UIImage imageNamed:@"Icon"];
        attachment.bounds = CGMakeRect(0, 0, attachment.image.size.width, attachment.image.size.height);
        return [[NSMutableAttributedString alloc] initWithAttributedString:[NSAttributedString attributedStringWithAttachment:attachment]];
    }
    return nil;
}
```

**Comment by kmaschke85** [comment]
Hi. Did you already had the chance to take a further look into my additions?

**Comment by mrataj** [comment]
Hey, sorry, I totally forgot about this.

I've merged your changes but I performed some cleanup on the code as well. Please look at this commit:
https://github.com/mrataj/BBCodeString/commit/3ec6ce83abec104be8a0739dfbdfc20b89985ff8

It should still solve your usecase, but you should use getAttributedTextForElement function instead of getCustomDefinedAttributedString

It's practically just the naming, so it's more unified with getTextForElement function which already existed before.

Let me know if this is ok with you, then I will submit new pod version

**Comment by kmaschke85** [comment]
I totally agree with these changes. Thanks a lot!

**Comment by mrataj** [comment]
Can you please test if this code works for you? I will submit new pod version if everything is ok

**Comment by kmaschke85** [comment]
Works like a charm!

**Comment by mrataj** [comment]
BBCodeString 0.2.2 is now available ;)

Thank you for your contribution!

**Pull request merged**
